global:
  scrape_interval: 15s

scrape_configs:
  - job_name: kafka_exporter
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: order_service
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: payment_service
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9104"]

  - job_name: inventory_service
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9102"]

  - job_name: notification_service
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9103"]
